export default function FAQs() {
    return (
        <section className="scroll-py-16 py-12 md:scroll-py-12 md:py-16">
            <div className="mx-auto max-w-5xl px-6">
                <div className="grid gap-y-12 px-2 lg:[grid-template-columns:1fr_auto]">
                    <div className="text-center lg:text-left">
                        <h2 className="mb-4 text-3xl font-semibold md:text-4xl">
                            Frequently <br className="hidden lg:block" /> Asked <br className="hidden lg:block" />
                            Questions
                        </h2>
                        <p className="text-muted-foreground">Everything you need to know about Cicero.</p>
                    </div>

                    <div className="divide-y divide-dashed sm:mx-auto sm:max-w-lg lg:mx-0">
                        <div className="pb-6">
                            <h3 className="font-medium">What meetings does Cicero cover?</h3>
                            <p className="text-muted-foreground mt-4">
                                Currently, Cicero covers Fort Collins City Council regular meetings and work sessions. 
                                We&apos;re starting with City Council because these meetings have the most direct impact 
                                on residents&apos; daily lives.
                            </p>
                        </div>
                        <div className="py-6">
                            <h3 className="font-medium">How accurate are the summaries?</h3>
                            <p className="text-muted-foreground mt-4">
                                Summaries are generated by AI from official meeting transcripts and agendas. While we strive 
                                for accuracy, these are summaries—not official records. For legal or official purposes, 
                                always refer to the city&apos;s official meeting minutes.
                            </p>
                        </div>
                        <div className="py-6">
                            <h3 className="font-medium">How quickly are summaries available?</h3>
                            <p className="text-muted-foreground mt-4">
                                Summaries are typically available within 24-48 hours after meeting videos are published 
                                by the city. Processing time depends on meeting length and video availability.
                            </p>
                        </div>
                        <div className="py-6">
                            <h3 className="font-medium">Is Cicero affiliated with the City of Fort Collins?</h3>
                            <p className="text-muted-foreground mt-4">
                                No. Cicero is an independent project. We use publicly available meeting videos and agendas 
                                from official city sources, but we are not endorsed by or affiliated with the City of Fort Collins.
                            </p>
                        </div>
                        <div className="py-6">
                            <h3 className="font-medium">Is this free?</h3>
                            <p className="text-muted-foreground mt-4">
                                Yes, Cicero is completely free to use. We believe civic information should be accessible 
                                to everyone. The project is open source and community-supported.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    )
}
